[NbConvertApp] Converting notebook DC2_Coadd_Run1.1p_GCR_access_--_HSC_selection.ipynb to notebook
[NbConvertApp] Executing notebook with kernel: desc-stack
/global/common/software/lsst/common/miniconda/kernels/stack.sh: illegal option -- f
/global/common/software/lsst/cori-haswell-gcc/stack//setup_current_sims.sh: line 20: module: command not found
/global/common/software/lsst/cori-haswell-gcc/stack//setup_current_sims.sh: line 21: module: command not found
/global/common/software/lsst/cori-haswell-gcc/stack//setup_current_sims.sh: line 22: module: command not found
/global/common/software/lsst/cori-haswell-gcc/stack//setup_current_sims.sh: line 23: module: command not found
/global/common/software/lsst/cori-haswell-gcc/stack//setup_current_sims.sh: line 24: module: command not found
/global/common/software/lsst/cori-haswell-gcc/stack//setup_current_sims.sh: line 25: module: command not found
/global/common/software/lsst/cori-haswell-gcc/stack//setup_current_sims.sh: line 26: module: command not found
Now setup any necessary stack packages such as: setup lsst_distrib or lsst_sims
[NbConvertApp] ERROR | Error while converting 'DC2_Coadd_Run1.1p_GCR_access_--_HSC_selection.ipynb'
Traceback (most recent call last):
  File "/usr/common/software/python/3.6-anaconda-4.4/lib/python3.6/site-packages/nbconvert/nbconvertapp.py", line 373, in export_single_notebook
    output, resources = self.exporter.from_filename(notebook_filename, resources=resources)
  File "/usr/common/software/python/3.6-anaconda-4.4/lib/python3.6/site-packages/nbconvert/exporters/exporter.py", line 171, in from_filename
    return self.from_file(f, resources=resources, **kw)
  File "/usr/common/software/python/3.6-anaconda-4.4/lib/python3.6/site-packages/nbconvert/exporters/exporter.py", line 189, in from_file
    return self.from_notebook_node(nbformat.read(file_stream, as_version=4), resources=resources, **kw)
  File "/usr/common/software/python/3.6-anaconda-4.4/lib/python3.6/site-packages/nbconvert/exporters/notebook.py", line 31, in from_notebook_node
    nb_copy, resources = super(NotebookExporter, self).from_notebook_node(nb, resources, **kw)
  File "/usr/common/software/python/3.6-anaconda-4.4/lib/python3.6/site-packages/nbconvert/exporters/exporter.py", line 131, in from_notebook_node
    nb_copy, resources = self._preprocess(nb_copy, resources)
  File "/usr/common/software/python/3.6-anaconda-4.4/lib/python3.6/site-packages/nbconvert/exporters/exporter.py", line 308, in _preprocess
    nbc, resc = preprocessor(nbc, resc)
  File "/usr/common/software/python/3.6-anaconda-4.4/lib/python3.6/site-packages/nbconvert/preprocessors/base.py", line 47, in __call__
    return self.preprocess(nb,resources)
  File "/usr/common/software/python/3.6-anaconda-4.4/lib/python3.6/site-packages/nbconvert/preprocessors/execute.py", line 211, in preprocess
    nb, resources = super(ExecutePreprocessor, self).preprocess(nb, resources)
  File "/usr/common/software/python/3.6-anaconda-4.4/lib/python3.6/site-packages/nbconvert/preprocessors/base.py", line 70, in preprocess
    nb.cells[index], resources = self.preprocess_cell(cell, resources, index)
  File "/usr/common/software/python/3.6-anaconda-4.4/lib/python3.6/site-packages/nbconvert/preprocessors/execute.py", line 242, in preprocess_cell
    raise CellExecutionError(msg)
nbconvert.preprocessors.execute.CellExecutionError: An error occurred while executing the following cell:
------------------
tract_number = 4850
mags = ['mag_g_lsst', 'mag_r_lsst', 'mag_i_lsst']
d = catalog.get_quantities(mags, 
                           filters=[GCRQuery((np.isfinite, key)) for key in mags] + ['mag_r_lsst < 25'], 
                           native_filters=[(lambda x: x==tract_number, 'tract')])
c = plt.scatter(d['mag_g_lsst'] - d['mag_r_lsst'], d['mag_r_lsst'] - d['mag_i_lsst'], s=2, c=d['mag_r_lsst']);
plt.colorbar(c, label='$r$')
plt.xlabel('$g-r$');
plt.ylabel('$r-i$');
------------------

ValueError: Native quantity `mag_g_lsst` does not exist (required by `mag_g_lsst`)

