[NbConvertApp] Converting notebook PhoSim_Instrumental_Configuration.ipynb to notebook
[NbConvertApp] Executing notebook with kernel: desc-stack
/global/common/software/lsst/common/miniconda/kernels/stack.sh: illegal option -- f
/global/common/software/lsst/cori-haswell-gcc/stack//setup_current_sims.sh: line 20: module: command not found
/global/common/software/lsst/cori-haswell-gcc/stack//setup_current_sims.sh: line 21: module: command not found
/global/common/software/lsst/cori-haswell-gcc/stack//setup_current_sims.sh: line 22: module: command not found
/global/common/software/lsst/cori-haswell-gcc/stack//setup_current_sims.sh: line 23: module: command not found
/global/common/software/lsst/cori-haswell-gcc/stack//setup_current_sims.sh: line 24: module: command not found
/global/common/software/lsst/cori-haswell-gcc/stack//setup_current_sims.sh: line 25: module: command not found
/global/common/software/lsst/cori-haswell-gcc/stack//setup_current_sims.sh: line 26: module: command not found
Now setup any necessary stack packages such as: setup lsst_distrib or lsst_sims
[NbConvertApp] ERROR | Error while converting 'PhoSim_Instrumental_Configuration.ipynb'
Traceback (most recent call last):
  File "/usr/common/software/python/3.6-anaconda-4.4/lib/python3.6/site-packages/nbconvert/nbconvertapp.py", line 373, in export_single_notebook
    output, resources = self.exporter.from_filename(notebook_filename, resources=resources)
  File "/usr/common/software/python/3.6-anaconda-4.4/lib/python3.6/site-packages/nbconvert/exporters/exporter.py", line 171, in from_filename
    return self.from_file(f, resources=resources, **kw)
  File "/usr/common/software/python/3.6-anaconda-4.4/lib/python3.6/site-packages/nbconvert/exporters/exporter.py", line 189, in from_file
    return self.from_notebook_node(nbformat.read(file_stream, as_version=4), resources=resources, **kw)
  File "/usr/common/software/python/3.6-anaconda-4.4/lib/python3.6/site-packages/nbconvert/exporters/notebook.py", line 31, in from_notebook_node
    nb_copy, resources = super(NotebookExporter, self).from_notebook_node(nb, resources, **kw)
  File "/usr/common/software/python/3.6-anaconda-4.4/lib/python3.6/site-packages/nbconvert/exporters/exporter.py", line 131, in from_notebook_node
    nb_copy, resources = self._preprocess(nb_copy, resources)
  File "/usr/common/software/python/3.6-anaconda-4.4/lib/python3.6/site-packages/nbconvert/exporters/exporter.py", line 308, in _preprocess
    nbc, resc = preprocessor(nbc, resc)
  File "/usr/common/software/python/3.6-anaconda-4.4/lib/python3.6/site-packages/nbconvert/preprocessors/base.py", line 47, in __call__
    return self.preprocess(nb,resources)
  File "/usr/common/software/python/3.6-anaconda-4.4/lib/python3.6/site-packages/nbconvert/preprocessors/execute.py", line 211, in preprocess
    nb, resources = super(ExecutePreprocessor, self).preprocess(nb, resources)
  File "/usr/common/software/python/3.6-anaconda-4.4/lib/python3.6/site-packages/nbconvert/preprocessors/base.py", line 70, in preprocess
    nb.cells[index], resources = self.preprocess_cell(cell, resources, index)
  File "/usr/common/software/python/3.6-anaconda-4.4/lib/python3.6/site-packages/nbconvert/preprocessors/execute.py", line 242, in preprocess_cell
    raise CellExecutionError(msg)
nbconvert.preprocessors.execute.CellExecutionError: An error occurred while executing the following cell:
------------------
column_names = [
    'amp_name',
    'x_low', 'x_high', 'y_low', 'y_high',
    'serial_read',
    'parallel_read',
    'gain', 
    'gain_var',
    'bias_level', 
    'bias_var',
    'read_noise', 
    'read_noise_var',
    'dark_current',
    'dark_current_var',
    'parallel_prescan', 
    'serial_overscan', 
    'serial_prescan', 
    'parallel_overscan',
    'hot_pixel_rate',
    'hot_column_rate',
    'bits_per_pixel',
    'X1', 'X2', 'X3', 'X4', 'X5', 'X6', 'X7', 'X8', 
    'X9', 'X10', 'X11', 'X12', 'X13', 'X14', 'X15', 'X16'
]

segmentation = pd.read_csv('segmentation.txt', delim_whitespace=True, comment="#", header=None,
                           names=column_names)
------------------

FileNotFoundError: File b'segmentation.txt' does not exist

